// components next
import Head from "next/head";
import Image, { StaticImageData } from "next/image";

// components
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import AuthProvider from "./provider";
import AuthContextProvider from "@/contexts/authContext";
import { ReduxProvider } from "@/redux/reduxProvider";

// css
import "./globals.css";

// metadata
import type { Metadata } from "next";

// image
import cinemaOnlineIcon from "@/assets/img/icon.png";
const favicon: StaticImageData = cinemaOnlineIcon;

// font
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cinema Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href={favicon.src} type="image/png" />
      </Head>
      <body className={inter.className}>
        <AuthProvider>
          <AuthContextProvider>
            <ReduxProvider>
              <Navbar />
              {children}
              <Footer />
            </ReduxProvider>
          </AuthContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
